name: Deploy React App to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
        type: choice
        options:
        - main
        - develop
        - staging

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy source code to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        source: "."
        target: "/var/www/source"
        
    - name: Build and deploy on VPS
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          npm --help
          cd /var/www/source
          sudo rm -rf node_modules
          npm ci
          npm run build
          sudo rm -rf /var/www/html/build/*
          sudo mkdir /var/www/html/build/
          sudo cp -r build/* /var/www/html/build/
          sudo chown -R www-data:www-data /var/www/html/build/
          sudo chmod -R 755 /var/www/html/build/
          echo "React app built and deployed successfully!"
